### ISSUE TITLE
ESMValTool climate data pre-processor

### ISSUE THREAD

**Issue by yifatdzigan** [c3s-magic/c3s-magic-metric-status#1]
This is a tracking issue for the final integration of *ESMValTool climate data pre-processor metric* into the MAGIC framework.

This is also a place for discussion and updates on the current status, problems and questions related to this metric.

**Links:**
----------

[Portal](https://portal.c3s-magic.eu/#/diagnostics/python_example)
[Recipe](https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/recipes/examples/recipe_preprocessor_test.yml)
For an overview of the current status of all metrics see [MAGIC Metrics Final Integration Checklist](https://docs.google.com/spreadsheets/d/1LFhEuL6w9KBqFmujVXXN6qj98jigMIPArYkSVKB_Frw/edit#gid=0)

**Contacts:**
--------------
@bouweandela 
@bjoernbroetz

**Comment by nielsdrost** [comment]
This metric is based on the Python example. If I recall correctly the only difference is the reference dataset being ERA-Interim instead of some model output.

**Comment by nielsdrost** [comment]
We've decided to use the python example as-is https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/recipes/examples/recipe_python.yml

Only differences from the standard recipe are in the datasets, and these are options in the WPS anyway (so the value in the standard recipe does not matter)

**Comment by yifatdzigan** [comment]
@bpmweel tested on DAS5. Ready for WPS integration.

**Comment by nielsdrost** [comment]
WPS done, including settings.

Output files do not all get rendered correctly, made an issue in the frontend: https://github.com/c3s-magic/c3s-magic-frontend/issues/220

**Comment by nielsdrost** [comment]
The default settings of this metric do not work as it adds the same model twice. Not sure this is too be helped though.
