### ISSUE TITLE
Generic multi-model products

### ISSUE THREAD

**Issue by yifatdzigan** [c3s-magic/c3s-magic-metric-status#11]
This is a tracking issue for the final integration of *Generic multi-model products metric* into the MAGIC framework.

This is also a place for discussion and updates on the current status, problems and questions related to this metric.

**Links:**
----------

[Portal](https://portal.c3s-magic.eu/#/diagnostics/anomaly_agreement)
[Recipe](https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/recipes/recipe_multimodel_products.yml)
For an overview of the current status of all metrics see [MAGIC Metrics Final Integration Checklist](https://docs.google.com/spreadsheets/d/1LFhEuL6w9KBqFmujVXXN6qj98jigMIPArYkSVKB_Frw/edit#gid=0)

**Contacts:**
--------------
@alasdairhunter 
@nmanuben

**Comment by yifatdzigan** [comment]
@yifatdzigan In the portal: we should update the back-end metric name from anomaly agreement to multi-model products

**Comment by yifatdzigan** [comment]
@bpmweel Recipe works on DAS5. Please integrate into WPS

**Comment by yifatdzigan** [comment]
@nperezzanon The recipe is for monthly tas, while the readthedocs mentions daily. Which one is correct?

**Comment by nperezzanon** [comment]
Hi @yifatdzigan,

I've just checked again on Jasmin and this recipe works with monthly data. It doesn't work with daily data because of differences between calendars in different models. 

Sorry for the mismatched.

Núria

**Comment by yifatdzigan** [comment]
I submitted a pull request to update the readthedocs

**Comment by lpcaron** [comment]
This function is missing many of the settings, like the model, start year, end year, historical vs rcp.

**Comment by rvanharen** [comment]
@Ipcaron Missing settings should be integrated now.

**Comment by lpcaron** [comment]
The media link doesn't work:  http://localhost:5000/static/diagnosticsdata/multimodel_products/bsc_anomaly_timeseries.png

**Comment by lpcaron** [comment]
I don't know what the link for Model Selection is supposed to be.

**Comment by lpcaron** [comment]
You have "integer" and "Integer" as explanation on the right.

**Comment by lpcaron** [comment]
The plots are cut off when they are displayed.

**Comment by lpcaron** [comment]
The functions only seems to work with 2 models. Attempts to run with 3 or 4 models have failed.

**Comment by yifatdzigan** [comment]
Static page updated with plots

**Comment by rvanharen** [comment]
> The functions only seems to work with 2 models. Attempts to run with 3 or 4 models have failed.

@Ipcaron Just tested with 3 models, works for me

**Comment by rvanharen** [comment]
> I don't know what the link for Model Selection is supposed to be.

It should not be pointing anywhere, but this is currently the only way we can get the information in the frontend

**Comment by lpcaron** [comment]
I just tried with MPI-ESM-MR, CMCC-CESM and GFDL-ESM2G and it's not working.

**Comment by lpcaron** [comment]
"Last month of the seasonal mean period to be computed, if none the monthly anomalies will be computed"

The null option is not available.

**Comment by lpcaron** [comment]
Also, we are missing the min/max for latitudes and longitudes.

**Comment by rvanharen** [comment]
> I just tried with MPI-ESM-MR, CMCC-CESM and GFDL-ESM2G and it's not working.

CMCC-CESM seems to be broken. I don't have time to check if it is the actual metric script that does not work with the model or that the model data somehow got corrupted. For now I suggest not using this model in this metric.

I tested with MPI-ESM-MR, ACCESS1-0, IPSL-CM5A-MR and IPSL-CM5B-LR and these work fine.

**Comment by rvanharen** [comment]
Also a more general note (also related to your comments in the other issues), I'm not sure how much if any we can still change before we make the release and deploy it for the demo tomorrow. Some things might have to wait for a bugfix release.

**Comment by lpcaron** [comment]
Indeed. It seems to work.

**Comment by lpcaron** [comment]
Min/max for latitudes and longitudes are missing.

**Comment by nperezzanon** [comment]
Hi,

Yes, the area selection is missing.

On the other hand, the 'historical' experiment could be selected and it makes me confuse.
The recipe needs the historical simulation as reference period, however, should the user select each model twice? one for the scenario and a second one for the historical period? Or it's automatically created by the wps, and the user just need to select the scenario. In the second case, would it make sense to have 'historical' as a choice?

Could it be the running mean be also setting as NULL?

Thanks,

Núria
