### ISSUE TITLE
Sub-ensemble selection

### ISSUE THREAD

**Issue by yifatdzigan** [c3s-magic/c3s-magic-metric-status#12]
This is a tracking issue for the final integration of *Sub-ensemble selection metric* into the MAGIC framework.

This is also a place for discussion and updates on the current status, problems and questions related to this metric.

**Links:**
----------

[Portal](https://portal.c3s-magic.eu/#/diagnostics/ensclus)
[Recipe](https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/recipes/recipe_ensclus.yml)
For an overview of the current status of all metrics see [MAGIC Metrics Final Integration Checklist](https://docs.google.com/spreadsheets/d/1LFhEuL6w9KBqFmujVXXN6qj98jigMIPArYkSVKB_Frw/edit#gid=0)

**Contacts:**
--------------
@jhardenberg

**Comment by jhardenberg** [comment]
There is a need to select also the experiment for this one (rcp45, rcp85 etc)
There should be a method for the user to select the models of interest:
Ideally a list of all available models with checkboxes would be a possibility.

**Comment by yifatdzigan** [comment]
@bpmweel tested on DAS5 and ready for WPS integration

**Comment by jhardenberg** [comment]
I repeat also here something I may have commented somewhere else (and this is true for alla diagnostics I believe):
In selecting the "experiment", when the future scenarios are selected (rcp26, rcp45, rcp85, rcp60), and the start date is <= 2005, it should still be possible to perform the computation (at the moment it fails) simply by creating a recipe where "exp" is a list, such as [historical, rcp45] ... This is actually understood by ESMValtool and should work correctly!

**Comment by yifatdzigan** [comment]
@jhardenberg could you please have a look in the readthedocs: https://github.com/ESMValGroup/ESMValTool/blob/version2_development/doc/sphinx/source/recipes/recipe_ensclus.rst and check if the variable section needs some refinement?

**Comment by bpmweel** [comment]
@jhardenberg The variable selection mentions that the user can choose. Not every model has every variable I understand. Could we come up with a relatively short list of interesting variables that we can let the user choose from?

**Comment by earnone** [comment]
The current approach of avoiding model selection for the user looks good to me for the demo. The page quotes "ACCESS1-0, ACCESS1-3, CanESM2, CCSM4, CESM1-BGC" whereas some 20 models are instead loaded by the recipe as shown in the log.

The calculation with default settings is however failing. I guess something is wrong when looking for the model files. 

@bpmweel Regarding variable, maybe for the demo we can restrict to temperature and precipitation, or also only precipitation as it is now. Then a sentence should be added on this in the calculation webpage. 

@yifatdzigan the documentation looks ok to me. We should only add some specific comments on the calculation webpage regarding the limited selection for the demo.

**Comment by jhardenberg** [comment]
The new model selection (specifying experiment and rip separately for each model and with the possibility to add several datasets) is exactly what we need, thank you!
In testing this and other recipes I noticed that currently it is not possible to change the starting and end years.

**Comment by jhardenberg** [comment]
Using the multiple model selection (I chose 4 datasets) the recipe which is created has still 30+ datasets in it, not only those which were selected. Subsequently the recipe fails because it does not find some of the data ...

**Comment by jhardenberg** [comment]
Please allow at least pr and tas to be selected for this metric (in general the wps should allow to specify the variable of interest)

**Comment by jhardenberg** [comment]
The selection "number of PCs" should be a numeric field and not a dropdown list so that the user can choose say 4, 6 etc PCs ...

**Comment by jhardenberg** [comment]
Issues with the landing page of this metric:
- In "Settings" , it says "Area: I" , while it should say "Area: EU"
- Both the figures on the page are outdated and the thumbnail too. Please use that currently in the recipe docs, https://esmvaltool.readthedocs.io/en/version2_development/_images/ensclus.png

**Comment by jhardenberg** [comment]
Issues in the landing page of this metric:
- In "Settings" It says that the "Variable" is geopotential height, but it should specify that it is at 500hPa (Z500)
- In the "Metric results" interactive plots
  - The buttons say "Select a layer" and "select a style" but in othe rmetrics the style or layer selected appears in the dropdown menu after selecting it.
-  It attempts to plot the "PCs timeseries" , which are timeseries, as a map, which obviously fails. 
- The colorbar labels say "-2.0, -1.0, -1.0, 0.0, 1.0, 2.0, 2.0" , this is obviously wrong. Also other metrics have this problem.

**Comment by jhardenberg** [comment]
Small typo: When displaying the results, it says "Clustering Statictics" -->that should be "Clustering Statistics" of course

**Comment by jhardenberg** [comment]
- Subensemble selection does not make much sense with only two models, please offer at least 3 or 4 models as default at the beginning.

**Comment by jhardenberg** [comment]
Running calculate for the diagnostic gives 
```
Results for process ensclus:
0) JSONObject["statuslocation"] not found.
Status link:
```
and nothing is added to the job list. This does not seem normal.

**Comment by nielsdrost** [comment]
Question in https://github.com/c3s-magic/c3s-magic-frontend/pull/257 by @jhardenberg : Would it be possible to change also the "metric results" with the same image?

**Comment by nielsdrost** [comment]
> Running calculate for the diagnostic gives
> 
> ```
> Results for process ensclus:
> 0) JSONObject["statuslocation"] not found.
> Status link:
> ```
> 
> and nothing is added to the job list. This does not seem normal.

Agreed. Will look into this (probably not until tomorrow though)

**Comment by nielsdrost** [comment]
> Question in [c3s-magic/c3s-magic-frontend#257](https://github.com/c3s-magic/c3s-magic-frontend/pull/257) by @jhardenberg : Would it be possible to change also the "metric results" with the same image?

This is the precalculated output we would normally use:
https://portal.c3s-magic.eu/data/recipes/recipe_ensclus_20190602_200903/plots/EnsClus/main/anomalies_pr_32ens_JJA_EU_CMIP5_historical.fig1.png

I would prefer to use that as it matches the downloadable one (eventually, this metric page still needs to be updated I think).

**Comment by yifatdzigan** [comment]
Landing page provenance doesn't work
