### ISSUE TITLE
combined indices - Tools to compute single and multi-model indices based on area averages

### ISSUE THREAD

**Issue by yifatdzigan** [c3s-magic/c3s-magic-metric-status#13]
This is a tracking issue for the final integration of *Tools to compute single and multi-model indices based on area averages metric* into the MAGIC framework.

This is also a place for discussion and updates on the current status, problems and questions related to this metric.

**Links:**
----------

[Portal](https://portal.c3s-magic.eu/#/diagnostics/combine_indices)
[Recipe](https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/recipes/recipe_combined_indices.yml)
For an overview of the current status of all metrics see [MAGIC Metrics Final Integration Checklist](https://docs.google.com/spreadsheets/d/1LFhEuL6w9KBqFmujVXXN6qj98jigMIPArYkSVKB_Frw/edit#gid=0)

**Contacts:**
--------------
@alasdairhunter 
@nmanuben

**Comment by nielsdrost** [comment]
Improvements done by @nperezzanon at the moment

**Comment by yifatdzigan** [comment]
@nperezzanon The recipe is for daily variables, while the readthedocs mentions monthly. Which one is correct?

**Comment by yifatdzigan** [comment]
@nperezzanon I merged the portal page pull request. FYI, the ACI component image doesn't look good (resolution is too small).

**Comment by nperezzanon** [comment]
Hi!
The final version of this recipe could be called just 'Tool to compute indices based on area averages'
It works with monthly data.
Do you need I provide a new plot with higher resolution or that should the recipe output increase the resolution?
Cheers, Núria

**Comment by lpcaron** [comment]
This function is missing many of the settings, like the model, start year, end year, historical vs rcp, and the regions to be selected.

**Comment by jhardenberg** [comment]
Just tested, esmvaltool fails

**Comment by rvanharen** [comment]
@Ipcaron Missing options should be implemented now.

**Comment by lpcaron** [comment]
This function should be renamed "indices based on area averages" as we are not doing multi-model averages.

**Comment by lpcaron** [comment]
The link for the documentation is wrong. It's that of another recipe.

**Comment by lpcaron** [comment]
In the region option, Nino is missing the ~.

**Comment by lpcaron** [comment]
Also, the function doesn't work with any models for any of the region that I've tried. This is one of the function I will use as a use cases.

**Comment by yifatdzigan** [comment]
File doesn't work on ADAGUC so interactive plot is disabled

**Comment by lpcaron** [comment]
We should remove the "multi-model" in the title as this function only does 1 model at the time.

**Comment by lpcaron** [comment]
The link in the documentation is still wrong.

**Comment by lpcaron** [comment]
This is one of the function I'm going to use for my use cases and it doesn't work.

I can't compute any of the Nino indices, including the SOI.

**Comment by nperezzanon** [comment]
Hi,
I have run the recipe in the portal an it just works for NAO, but not for the rest of available regions.
However, I am running it on Jasmin at it works for me. 

The variable cannot be selected.
I would be fine if the recipe uses 'psl' when NAO region is selected and 'tos' for the rest of regions.
However, in the second case, 'tos' you will need to add a preprocessor to regrid to 1x1.

Thanks,

Núria

**Comment by lpcaron** [comment]
SOI should work with psl as well.
