### ISSUE TITLE
Teleconnection

### ISSUE THREAD

**Issue by yifatdzigan** [c3s-magic/c3s-magic-metric-status#15]
This is a tracking issue for the final integration of *Teleconnection metric* into the MAGIC framework.

This is also a place for discussion and updates on the current status, problems and questions related to this metric.

**Links:**
----------

[Portal](https://portal.c3s-magic.eu/#/diagnostics/teleconnections)
[Recipe](https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/recipes/recipe_miles_eof.yml)
For an overview of the current status of all metrics see [MAGIC Metrics Final Integration Checklist](https://docs.google.com/spreadsheets/d/1LFhEuL6w9KBqFmujVXXN6qj98jigMIPArYkSVKB_Frw/edit#gid=0)

**Contacts:**
--------------
@jhardenberg
@earnone

**Comment by yifatdzigan** [comment]
@bpmweel Recipe works. Ready for WPS integration

**Comment by bpmweel** [comment]
@jhardenberg Could you please try again, for it works now. Do you have any other comments besides the reference model and model choice list as mentioned in the other issues?

**Comment by jhardenberg** [comment]
I tried not changing the defaults and unfortunately it still fails.

**Comment by earnone** [comment]
I am afraid this is also failing because it cannot find the model data.

**Comment by jhardenberg** [comment]
* The recipe computes 4 teleconnection patterns, but the “data” panel only shows one of them  (confusingly the last one)
* Including the “PC Timeseries” in the “data” plot does not make much sense, since this is a timeseries, and it produces a meaningless plot.
These problems probably apply also to the blocking diagnostic.

**Comment by rvanharen** [comment]
>     * The recipe computes 4 teleconnection patterns, but the “data” panel only shows one of them  (confusingly the last one)
> 
>     * Including the “PC Timeseries” in the “data” plot does not make much sense, since this is a timeseries, and it produces a meaningless plot.
>       These problems probably apply also to the blocking diagnostic.

Just tested on https://portal.c3s-magic.eu/#/calculate/copernicus-wps/teleconnections
- Showing of all 4 teleconnection patterns seems to be fixed
- We currently cannot fix what variables from the netCDF file are shown in the frontend.

**Comment by jhardenberg** [comment]
After getting feedback from a coauthor, we updated the description of the diagnostic in the landing page (diagnostics & metrics). I prepared directly a PR, which you just need to accept:
https://github.com/c3s-magic/c3s-magic-frontend/pull/253

**Comment by yifatdzigan** [comment]
> After getting feedback from a coauthor, we updated the description of the diagnostic in the landing page (diagnostics & metrics). I prepared directly a PR, which you just need to accept:
> [c3s-magic/c3s-magic-frontend#253](https://github.com/c3s-magic/c3s-magic-frontend/pull/253)

Was merged. Static page updated.
