### ISSUE TITLE
Climate Variability Diagnostics

### ISSUE THREAD

**Issue by yifatdzigan** [c3s-magic/c3s-magic-metric-status#2]
This is a tracking issue for the final integration of *Climate Variability Diagnostics metric* into the MAGIC framework.

This is also a place for discussion and updates on the current status, problems and questions related to this metric.

**Links:**
----------

[Portal](https://portal.c3s-magic.eu/#/diagnostics/cvdp)
[Recipe](https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/recipes/recipe_cvdp.yml)
For an overview of the current status of all metrics see [MAGIC Metrics Final Integration Checklist](https://docs.google.com/spreadsheets/d/1LFhEuL6w9KBqFmujVXXN6qj98jigMIPArYkSVKB_Frw/edit#gid=0)

**Contacts:**
--------------
@bjoernbroetz

**Comment by yifatdzigan** [comment]
@bpmweel Recipe works. Ready for WPS integration

**Comment by jhardenberg** [comment]
Diagnostic runs in the WPS but produces no plots, see https://github.com/ESMValGroup/ESMValTool/pull/1076

**Comment by bpmweel** [comment]
Showing of results is fixed and tested on portal.c3s-magic.eu. After the linked ESMValtool pull request is merged we need to update the WPS process as well.
