### ISSUE TITLE
Consecutive Dry Days

### ISSUE THREAD

**Issue by yifatdzigan** [c3s-magic/c3s-magic-metric-status#21]
This is a tracking issue for the final integration of *Consecutive Dry Days
 metric* into the MAGIC framework.

This is also a place for discussion and updates on the current status, problems and questions related to this metric.

**Links:**
----------

[Portal](https://portal.c3s-magic.eu/#/diagnostics/consecdrydays)
[Recipe](https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/recipes/recipe_consecdrydays.yml)
For an overview of the current status of all metrics see [MAGIC Metrics Final Integration Checklist](https://docs.google.com/spreadsheets/d/1LFhEuL6w9KBqFmujVXXN6qj98jigMIPArYkSVKB_Frw/edit#gid=0)

**Contacts:**
--------------
@PeterBergSMHI

**Comment by yifatdzigan** [comment]
@PeterBergSMHI @bouweandela 
@rvanharen tested recipe_consecdrydays on DAS5 and it failed:

- recipe_consecdrydays.yml: 
-> adding the following code block after variales - pr, the recipe completes, not sure if this is the correct fix 
```       
start_year: 2001
end_year: 2002
mip: day
```

**Comment by rvanharen** [comment]
Debug output of the recipe in version2_development branch:
[main_log_debug.txt](https://github.com/c3s-magic/c3s-magic-metric-status/files/3134049/main_log_debug.txt)

**Comment by yifatdzigan** [comment]
@bpmweel Recipe works on DAS5. Please integrate into WPS

**Comment by bouweandela** [comment]
> tested recipe_consecdrydays on DAS5 and it failed

This bug is fixed now, there is no need for the workaround.

**Comment by bpmweel** [comment]
@PeterBergSMHI Could you please take a look at the wps page (https://portal-dev.c3s-magic.eu/#/calculate/copernicus-wps/consecdrydays) to check whether you have any feedback. If not we will consider it completed for the wps.

**Comment by PeterBergSMHI** [comment]
As long as one sticks to ACCES1-0 things seem to work fine. I tried a few, but could not find another model that worked. But I think that might be due to the availability of daily pr data. If you know another model that should work, it would be good if you can test that.

The only issue I find when running ACCES1-0 data are the tabs with a map where one can chose different layers and projections, which do not show any data at all. Should it work? The first of those tabs is named "Data Drymax - (data_drymax)".

**Comment by jhardenberg** [comment]
A comment as a user who does not know much about this diagnostic:
What are the `frlim` and `prlim` parameters?  These need an explanation.
