### ISSUE TITLE
Time series of data relevant for the water sector

### ISSUE THREAD

**Issue by yifatdzigan** [c3s-magic/c3s-magic-metric-status#22]
This is a tracking issue for the final integration of *Time series of data relevant for the water sector metric* into the MAGIC framework.

This is also a place for discussion and updates on the current status, problems and questions related to this metric.

**Links:**
----------

[Portal](https://portal.c3s-magic.eu/#/diagnostics/shapefile_selection)
[Recipe](https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/recipes/recipe_shapeselect.yml)
For an overview of the current status of all metrics see [MAGIC Metrics Final Integration Checklist](https://docs.google.com/spreadsheets/d/1LFhEuL6w9KBqFmujVXXN6qj98jigMIPArYkSVKB_Frw/edit#gid=0)

**Contacts:**
--------------
@PeterBergSMHI

**Comment by yifatdzigan** [comment]
@PeterBergSMHI Could you please provide a link to the yml file with the recipe?

**Comment by PeterBergSMHI** [comment]
https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/recipes/recipe_shapeselect.yml

Peter

________________________________

**Comment by yifatdzigan** [comment]
@PeterBergSMHI @bouweandela 
@rvanharen tested recipe_consecdrydays on DAS5 and it failed:

- recipe_consecdrydays.yml: 
-> adding the following code block after variales - pr, the recipe completes, not sure if this is the correct fix 
```       
start_year: 2001
end_year: 2002
mip: day
```

**Comment by yifatdzigan** [comment]
@bpmweel Recipe works on DAS5. Please integrate into WPS

**Comment by yifatdzigan** [comment]
@PeterBergSMHI Could you have a look at the readthedocs: https://github.com/ESMValGroup/ESMValTool/blob/version2_development/doc/sphinx/source/recipes/recipe_shapeselect.rst and see if the variables sections needs refinements?

**Comment by nielsdrost** [comment]
This metric could perhaps use a bit more shapefiles.

**Comment by nielsdrost** [comment]
@PeterBergSMHI we currently use the 5 "example" shapes for the process. Uploading custom shapes is probably not something we can support right now, but we could add a few more "nice" shapes. Do you happen to have some relevant shapes for this metric?

**Comment by PeterBergSMHI** [comment]
It could, but the main idea and usefulness is for water managers to provide their own shapefiles. In the portal we are only presenting the tool with some examples. I'm afraid we cannot provide more examples now as we are quite busy with other projects, and larger data bases such as hydrosheds do not fulfil the licensing requirements.
I think we should be content with what we have unless there is a specific issue raised; to be only "ambitious enough" close to the deadline.

**Comment by nielsdrost** [comment]
@PeterBergSMHI thanks. It would be ease to expose custom shape upload via the wps, so perhaps we will add a note somewhere what this would be a possible extention.

**Comment by yifatdzigan** [comment]
The file doesn't work on ADAGUC so I disabled it for this metric.
