### ISSUE TITLE
Heatwaves and Coldwaves

### ISSUE THREAD

**Issue by yifatdzigan** [c3s-magic/c3s-magic-metric-status#24]
This is a tracking issue for the final integration of *Heatwaves and Coldwaves metric* into the MAGIC framework.

This is also a place for discussion and updates on the current status, problems and questions related to this metric.

**Links:**
----------

[Portal](https://portal.c3s-magic.eu/#/diagnostics/extreme_spells)
[Recipe](https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/recipes/recipe_heatwaves_coldwaves.yml)
For an overview of the current status of all metrics see [MAGIC Metrics Final Integration Checklist](https://docs.google.com/spreadsheets/d/1LFhEuL6w9KBqFmujVXXN6qj98jigMIPArYkSVKB_Frw/edit#gid=0)

**Contacts:**
--------------
@alasdairhunter 
@nmanuben

**Comment by yifatdzigan** [comment]
@yifatdzigan we should correct the name of this metric in the portal

**Comment by yifatdzigan** [comment]
@bpmweel Recipe works on DAS5. Please integrate into WPS

**Comment by lpcaron** [comment]
I've tried using this function and I cannot change the following settings:
Start historical
End historical
Start projection
End projection
Quantile:
Minimum duration

**Comment by lpcaron** [comment]
I ran with GFDL-CM3, r2i1p1
Operator: exceedance
Season summer. 

I get an the following error message: Process failed, please check server error log

**Comment by lpcaron** [comment]
Playing with the different settings returns the same error message.

**Comment by jhardenberg** [comment]
The description text "either `>` for exceedances or `<` for non-exceedances" is not really consistent with the dropdown options. Maybe use "Select exceedances or non-exceedances" (the authors of this metric may offer better advice)

**Comment by lpcaron** [comment]
The link for Media doesn't work.

**Comment by lpcaron** [comment]
The user probably shouldn't be allowed to have negative quantiles.

**Comment by lpcaron** [comment]
The description on the right should all start with a capital letter.

**Comment by lpcaron** [comment]
Also, the recipe doesn't seem to work for the summer season.

**Comment by yifatdzigan** [comment]
File doesn't work in  ADAGUC so removed the interactive plot.

**Comment by lpcaron** [comment]
The recipe mentions tasmin when computing heatwaves. Not sure whether the problem is just a typo or a problem with the recipe. Will discuss with @nperezzanon  tomorrow.

**Comment by lpcaron** [comment]
Also, the min/max for latitudes and longitudes are missing.

**Comment by lpcaron** [comment]
The user should be able to select tasmax or tasmin. Currently, only tasmin is used.
