### ISSUE TITLE
Diurnal Temperature Variation (DTR) Indicator

### ISSUE THREAD

**Issue by yifatdzigan** [c3s-magic/c3s-magic-metric-status#25]
This is a tracking issue for the final integration of *Diurnal Temperature Variation (DTR) Indicator

This is also a place for discussion and updates on the current status, problems and questions related to this metric.

**Links:**
----------

[Portal](https://portal.c3s-magic.eu/#/diagnostics/dtr)
[Recipe](https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/recipes/recipe_diurnal_temperature_index.yml)
For an overview of the current status of all metrics see [MAGIC Metrics Final Integration Checklist](https://docs.google.com/spreadsheets/d/1LFhEuL6w9KBqFmujVXXN6qj98jigMIPArYkSVKB_Frw/edit#gid=0)

**Contacts:**
--------------
@alasdairhunter 
@nmanuben

**Comment by yifatdzigan** [comment]
@bpmweel Recipe works on DAS5. Please integrate into WPS

**Comment by lpcaron** [comment]
I had a look at this function and I can only change the model, choose between historical and rcp26 scenario and the members. I cannot change the region nor any of the dates.

**Comment by rvanharen** [comment]
@Ipcaron Thanks, we have implemented the dates selection and lon/lat selection.

**Comment by lpcaron** [comment]
Would it be possible to have the default values as
Start historical: 1990
End historical: 2000
Start projection: 2070
End projection: 2080

It will make the use cases run faster.

**Comment by lpcaron** [comment]
Also, "minimum" and "maximum" should be written with capital letters.

**Comment by nielsdrost** [comment]
> Would it be possible to have the default values as
> Start historical: 1990
> End historical: 2000
> Start projection: 2070
> End projection: 2080
> 
> It will make the use cases run faster.

done
