### ISSUE TITLE
Capacity Factor

### ISSUE THREAD

**Issue by yifatdzigan** [c3s-magic/c3s-magic-metric-status#26]
This is a tracking issue for the final integration of *Capacity Factor metric* into the MAGIC framework.

This is also a place for discussion and updates on the current status, problems and questions related to this metric.

**Links:**
----------

[Portal](https://portal.c3s-magic.eu/#/diagnostics/capacity_factor)
[Recipe](https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/recipes/recipe_capacity_factor.yml)
For an overview of the current status of all metrics see [MAGIC Metrics Final Integration Checklist](https://docs.google.com/spreadsheets/d/1LFhEuL6w9KBqFmujVXXN6qj98jigMIPArYkSVKB_Frw/edit#gid=0)

**Contacts:**
--------------
@alasdairhunter 
@nmanuben

**Comment by yifatdzigan** [comment]
@bpmweel Recipe works on DAS5. Please integrate into WPS

**Comment by lpcaron** [comment]
Just reviewed this function and the settings do not appear.

**Comment by jhardenberg** [comment]
Just tested, diagnostic fails

**Comment by yifatdzigan** [comment]
The file doesn't work on ADAGUC so it is disabled.

**Comment by jhardenberg** [comment]
Using default settings the metric fails  looking for files matching ['sfcWind_day_MPI-ESM-MR_rcp85_r1i1p1_*.nc'] in ['/cmip5/MPI-M/MPI-ESM-MR/rcp85/day/atmos/day/r1i1p1/sfcWind/latest']
Maybe those data are not available?

**Comment by jhardenberg** [comment]
Small inconistency:
The option "season": it is small caps (like "djf") while other diagnostics use "DJF" (all caps)

**Comment by lpcaron** [comment]
I tried running with MPI-ESM-MR, GFDL-ESM2G, CMCC-CESM and IPSL-CM5A-Mr for years 2025-2030 (rcp85) and they all failed. This is supposed to be one of my use cases for the demo.

**Comment by jhardenberg** [comment]
The description says "as described in Lled?? (2017)" some special character is wrong.

**Comment by lpcaron** [comment]
It should be Lledó. And the reference can be updated to 
Lledó, Ll., V. Torralba, A. Soret, J. Ramon, F.J. Doblas-Reyes (2019). Seasonal forecasts of wind power generation, Renewable Energy, 143, 91-100, doi:10.1016/j.renene.2019.04.135

**Comment by yifatdzigan** [comment]
> It should be Lledó. And the reference can be updated to
> Lledó, Ll., V. Torralba, A. Soret, J. Ramon, F.J. Doblas-Reyes (2019). Seasonal forecasts of wind power generation, Renewable Energy, 143, 91-100, doi:10.1016/j.renene.2019.04.135

Fixed the reference. Will be shown once the portal is finished (later today?).

**Comment by rvanharen** [comment]
> I tried running with MPI-ESM-MR, GFDL-ESM2G, CMCC-CESM and IPSL-CM5A-Mr for years 2025-2030 (rcp85) and they all failed. This is supposed to be one of my use cases for the demo.

@Ipcaron Just tested with MPI-ESM-MR for 2025-2030 rcp85 and using defaults for the rest, works for me now.

**Comment by rvanharen** [comment]
> Small inconistency:
> The option "season": it is small caps (like "djf") while other diagnostics use "DJF" (all caps)

made a PR for this

**Comment by lpcaron** [comment]
Could we have the default coordinates to: 
Start longitude: 240
End longitude: 285
Start latitude: 27
End latitude: 50 

It's what I'll use for my use cases.

**Comment by lpcaron** [comment]
Would it be possible to add the following table in the documentation of the function? I'm sure ECMWF will ask for it.

https://esmvaltool.readthedocs.io/en/version2_development/recipes/recipe_capacity_factor.html
Main features of the selected turbines
.
IEC Class  Turbine name  Rotor  diameter (m) Rated power (MW) Cut-in-speed (m/s) Rated speed (m/s) Cut-out speed (m/s)
Class I Enercon E70_2.3MW           70     2.3  2.0  16.0    25.0
Class I/II     Gamesa G80_2.0MW   80    2.0  4.0  17.0    25.0
Class II       Gamesa G87_2.0MW   87    2.0  4.0  16.0    25.0
Class II/III   Vestas V100_2.0MW    100   2.0  3.0  15.0   20.0
Class III      Vestas V110_2.0MW    110   2.0  3.0  11.5   20.0

**Comment by lpcaron** [comment]
The reference in the documentation (https://esmvaltool.readthedocs.io/en/version2_development/recipes/recipe_capacity_factor.html)
can be updated to 
Lledó, Ll., V. Torralba, A. Soret, J. Ramon, F.J. Doblas-Reyes (2019). Seasonal forecasts of wind power generation, Renewable Energy, 143, 91-100, doi:10.1016/j.renene.2019.04.135

**Comment by jhardenberg** [comment]
Hi @lpcaron , to update the ESMValTool documentation you could edit directly the corresponding source file `https://github.com/ESMValGroup/ESMValTool/blob/version2_development/doc/sphinx/source/recipes/recipe_capacity_factor.rst`
and from there initiate a pull request to get it included in ESMValTool. It will not be done in time for the demo tomorrow but it should be a quite straightforward process...

**Comment by nielsdrost** [comment]
> Hi @lpcaron , to update the ESMValTool documentation you could edit directly the corresponding source file `https://github.com/ESMValGroup/ESMValTool/blob/version2_development/doc/sphinx/source/recipes/recipe_capacity_factor.rst`
> and from there initiate a pull request to get it included in ESMValTool. It will not be done in time for the demo tomorrow but it should be a quite straightforward process...

If you do a pull request of only that one rst file I would not be surprised if it can be merged in an hour or so.

**Comment by nielsdrost** [comment]
> Could we have the default coordinates to:
> Start longitude: 240
> End longitude: 285
> Start latitude: 27
> End latitude: 50
> 
> It's what I'll use for my use cases.

Done, see https://github.com/c3s-magic/c3s-magic-wps/pull/72
