### ISSUE TITLE
Combined Climate Extreme Index

### ISSUE THREAD

**Issue by yifatdzigan** [c3s-magic/c3s-magic-metric-status#27]
This is a tracking issue for the final integration of *Combined Climate Extreme Index metric* into the MAGIC framework.

This is also a place for discussion and updates on the current status, problems and questions related to this metric.

**Links:**
----------

[Portal](https://portal.c3s-magic.eu/#/diagnostics/risk_index)
[Recipe](https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/recipes/recipe_extreme_index.yml)
For an overview of the current status of all metrics see [MAGIC Metrics Final Integration Checklist](https://docs.google.com/spreadsheets/d/1LFhEuL6w9KBqFmujVXXN6qj98jigMIPArYkSVKB_Frw/edit#gid=0)

**Contacts:**
--------------
@alasdairhunter 
@nmanuben

**Comment by nielsdrost** [comment]
Portal page should be renamed

**Comment by lpcaron** [comment]
There are no settings to choose for this metric.

**Comment by jhardenberg** [comment]
Just tested, seems to fail

**Comment by rvanharen** [comment]
@jhardenberg Thanks for testing. I'll add it to the todo list for tomorrow.

**Comment by lpcaron** [comment]
In the description, "integer" should be "Integer"

**Comment by lpcaron** [comment]
The plots are cut off.

**Comment by yifatdzigan** [comment]
file doesn't work in ADAGUC so it is disabled

**Comment by lpcaron** [comment]
This function is missing the min/max latitudes and longitudes.

**Comment by lpcaron** [comment]
So we can't select the region over which to run the diagnostic. Right now, it's mostly over the ocean, which for this index doesn't make much sense.

**Comment by nielsdrost** [comment]
> So we can't select the region over which to run the diagnostic. Right now, it's mostly over the ocean, which for this index doesn't make much sense.

Region is set in ESMValTool recipe.

Added settings, see https://github.com/c3s-magic/c3s-magic-wps/pull/76

**Comment by lpcaron** [comment]
I noticed during the demo session that this metric doesn't have the same name here:
https://portal.c3s-magic.eu/#/tailoredproduct_actuaries (this is the old name)
as it does here:
https://portal.c3s-magic.eu/#/diagnostics/extreme_index

Also, it used to display per country, as the first link above shows. 

I gather this feature was abandoned?

**Comment by nperezzanon** [comment]
Hi @nilsdrost,

Now I can see the settings for selecting the area and the reference and future periods, however I cannot modify them.

I am also missing some settings that are included in the scripts field of the recipe:
        - weight_t90p: 0.2      weight for maximum extreme temperature indicator
        - weight_t10p: 0.2      weight for minimum extreme temperature indicator
        - weight_Wx: 0.2        weight for extreme wind indicator
        - weight_rx5day: 0.2  weight for extreme precipitation indicator
        - weight_cdd: 0.2       weight for extreme drough indicator

I think this can be solved in the wps.

Cheers,

Núria
