### ISSUE TITLE
Common issues for Blocking, Teleconnections, Weather Regimes

### ISSUE THREAD

**Issue by jhardenberg** [c3s-magic/c3s-magic-metric-status#30]
Since `start year` and `end year ` are used both for the dataset and for the reference, it is actually not possible to apply the diagnostic to future scenarios. E.g. if I choose 2020-2050 it will try to apply these dates both to the model and to ERA-Interim. We should have two separate starting and ending dates for models and reference (should be fixed, but no need to do it for the demo)

**Comment by jhardenberg** [comment]
The MiLES Blocking and Teleconnections recipes both allow the user to specify also custom months over which to perform the analysis specifying `seasons` as e.g.  "Jan_Feb_Mar"  instead of "DJF" etc.
During the demo we got feedback that selecting for example individual months would be a desiderable feature. Since the functionality is already in place in the ESMValtool diagnostic, can we expose it somehow?

**Comment by nielsdrost** [comment]
Moved, see:

- https://github.com/c3s-magic/c3s-magic-wps/issues/94
- https://github.com/c3s-magic/c3s-magic-wps/issues/95
