### ISSUE TITLE
Extreme Events

### ISSUE THREAD

**Issue by yifatdzigan** [c3s-magic/c3s-magic-metric-status#9]
This is a tracking issue for the final integration of *Extreme Events metric* into the MAGIC framework.

This is also a place for discussion and updates on the current status, problems and questions related to this metric.
**Links:**
----------

Portal page does not exist yet.
[Recipe](https://github.com/ESMValGroup/ESMValTool/blob/version2_ExtremeEvents/esmvaltool/recipes/recipe_ExtremeEvents.yml)
For an overview of the current status of all metrics see [MAGIC Metrics Final Integration Checklist](https://docs.google.com/spreadsheets/d/1LFhEuL6w9KBqFmujVXXN6qj98jigMIPArYkSVKB_Frw/edit#gid=0)

**Contacts:**
--------------
@bjoernbroetz 
@maritsandstad

**Comment by jhardenberg** [comment]
We made some progress in the metric, which is now working standalone (no provenance yet): https://github.com/ESMValGroup/ESMValTool/issues/270 . A PR should follow soon.

**Comment by jhardenberg** [comment]
There is now a PR: https://github.com/ESMValGroup/ESMValTool/pull/1052 
The diagnostic seems to work correctly, passes all tests, provenance added.

**Comment by jhardenberg** [comment]
We are missing a diagnostic description page for this metric. All the needed info text and example figures are actually available in the sphinx docs of the diagnostic. How can we proceed? What else is needed ?

**Comment by yifatdzigan** [comment]
@jhardenberg Could you please provide me with a link to the text and the figures, so I can prepare an initial page for the diagnostic?
Thanks!

**Comment by jhardenberg** [comment]
hello @yifatdzigan ,
as we offered to Neils today during the project telco, we could prepare a draft landing page for the diagnostic ourselves today and initiate a PR for the c3s-magic-frontend. Would that be ok for you?

**Comment by jhardenberg** [comment]
Hi, we just prepared a PR for the landing page for this metric here:
https://github.com/c3s-magic/c3s-magic-frontend/pull/236

**Comment by earnone** [comment]
The doi in the Sillmann 2013 reference is wrong. This is the correct one: https://doi.org/10.1002/jgrd.50203

**Comment by earnone** [comment]
@rvanharen the "settings" on the [portal page](https://portal.c3s-magic.eu/#/diagnostics/extreme_events) crop the lists. That should be wrapped in new lines as for other metrics.

**Comment by jhardenberg** [comment]
The settings open with two default models. 
- It would be better to have a selection of at least three models. 
- Currently the same model is offered twice, would it be possible to start with two (three) different models?
- It is not possible to select the indices to be computed, which indices will be computed?

- Description text is wrong, this should be "Producing Glecker and timeline plots of this as shown in the IPCC_AR5 report"

**Comment by yifatdzigan** [comment]
> The doi in the Sillmann 2013 reference is wrong. This is the correct one: https://doi.org/10.1002/jgrd.50203

fixed

**Comment by yifatdzigan** [comment]
>     * Description text is wrong, this should be "Producing Glecker and timeline plots of this as shown in the IPCC_AR5 report"
Fixed.

**Comment by yifatdzigan** [comment]
The settings in the static diagnostic page needs to be updated according to the recipe

**Comment by earnone** [comment]
> The settings in the static diagnostic page needs to be updated according to the recipe

@yifatdzigan do you mean according to the default settings in the recipe?

**Comment by rvanharen** [comment]
> The settings open with two default models.
> 
>     * It would be better to have a selection of at least three models.
> 
>     * Currently the same model is offered twice, would it be possible to start with two (three) different models?
> 
>     * It is not possible to select the indices to be computed, which indices will be computed?
> 
>     * Description text is wrong, this should be "Producing Glecker and timeline plots of this as shown in the IPCC_AR5 report"

@jhardenberg 

- Clicking the plus sign the user can add another model
- It is a known issue that the second (and further) model is the same as the first one, it is not something we can fix before the demo
- All indices are computed
- Description is fixed

**Comment by rvanharen** [comment]
> @rvanharen the "settings" on the [portal page](https://portal.c3s-magic.eu/#/diagnostics/extreme_events) crop the lists. That should be wrapped in new lines as for other metrics.

@earnone @yifatdzigan is going through all the portal pages to make sure they look correct, it needs some spaces added to be displayed correctly

**Comment by jhardenberg** [comment]
Some important settings are missing:
1) The choice of the indices to compute (`timeseries_idx` and `gleckler_idx`). These control which indices are computed separately for timeseries and gleckler plot, but they could be both set to the same for simplicity
2) `base_range` the starting and end years compared to which the indices are computed (e.g. the period in which to compute reference percentiles)
3) `analysis_range`: the range of years to be used for the analysis
